import turtle

screen = turtle.Screen()
screen.screensize(800,800)
screen.bgcolor('light steel blue')
window=turtle.Screen()
t=turtle.Turtle()
s=t.getscreen()
s.bgcolor('lightblue')

t_g = turtle.Turtle()
t_g.penup()
t_g.speed(0)
t_g.fillcolor('snow1')
t_g.goto(-1000,0)
t_g.pendown()
t_g.begin_fill()
t_g.goto(1000,0)
t_g.goto(1000,-1000)
t_g.goto(-1000,-1000)
t_g.goto(-1000,0)
t_g.end_fill()
t.speed(0)
t.color('green')
t.pensize(5)
t.begin_fill()

t.forward(100)
t.left(150)
t.forward(90)
t.right(150)
t.forward(60)
t.left(150)
t.forward(60)
t.right(150)
t.forward(40)
t.left(150)
t.forward(100)
t.end_fill()

t.begin_fill()
t.left(60)
t.forward(100)
t.left(150)
t.forward(40)
t.right(150)
t.forward(60)
t.left(150)
t.forward(60)
t.right(150)
t.forward(90)
t.left(150)
t.forward(133)
t.end_fill()

t.pencolor('brown')
t.pensize(1)
t.fillcolor('brown')
t.begin_fill()
t.right(90)
t.forward(80)
t.right(90)
t.forward(40)
t.right(90)
t.forward(80)
t.end_fill()

t.penup()
t.color('red')
t.goto(110,-10)
t.begin_fill()
t.circle(10)
t.end_fill()

t.penup()
t.color('red')
t.goto(-120,-10)
t.begin_fill()
t.circle(10)
t.end_fill()

t.penup()
t.color('pink')
t.goto(100,40)
t.begin_fill()
t.circle(10)
t.end_fill()

t.penup()
t.color('pink')
t.goto(-105,38)
t.begin_fill()
t.circle(10)
t.end_fill()

t.penup()
t.color('red')
t.goto(85,70)
t.begin_fill()
t.circle(7)
t.end_fill()

t.penup()
t.color('red')
t.goto(-95,70)
t.begin_fill()
t.circle(7)
t.end_fill()

t.shape('triangle')
t.fillcolor('pink')
t.goto(-20,30)
t.setheading(90)
t.stamp()
t.fillcolor('red')
t.goto(20,60)
t.setheading(90)
t.stamp()
t.goto(-40,75)
t.setheading(90)
t.stamp()

t.speed(5)
t.penup()
t.color('pink')
t.goto(-20,110)
t.begin_fill()
t.pendown()

t.penup()


message="Merry Christmas Queens!"
t.goto(0,200)
t.color('green')
t.write(message,move=False,align='center',font=('Arilal',20,'bold'))

t.hideturtle()


t_present = turtle.Turtle()
t_present.speed(0)
t_present.hideturtle()
t_present.speed(0)
t_present.penup()
t_present.goto(-65,-250)
t_present.pendown()
t_present.fillcolor("red")
t_present.begin_fill()
t_present.forward(50)
t_present.left(90)
t_present.forward(50)
t_present.left(90)
t_present.forward(50)
t_present.left(90)
t_present.forward(50)
t_present.left(90)
t_present.end_fill()
t_present.penup()
t_present.goto(-40,-250)
t_present.pendown()
t_present.fillcolor("gold")
t_present.begin_fill()
t_present.forward(5)
t_present.left(90)
t_present.forward(50)
t_present.left(90)
t_present.forward(5)
t_present.left(90)
t_present.forward(50)
t_present.left(90)
t_present.end_fill()
t_present.penup()
t_present.goto(-65,-225)
t_present.pendown()
t_present.fillcolor("gold")
t_present.begin_fill()
t_present.forward(50)
t_present.left(90)
t_present.forward(5)
t_present.left(90)
t_present.forward(50)
t_present.left(90)
t_present.forward(5)
t_present.left(90)
t_present.end_fill()


candy = turtle.Turtle()
candy.pensize(5)
candy.color("red")

candy.penup()
candy.goto(100, 100)
candy.pendown()
candy.setheading(90)
candy.forward(50)
candy.right(90)
candy.forward(10)
candy.right(90)
candy.forward(10)
candy.penup()
candy.goto(100, 100)
candy.pendown()
candy.hideturtle()
t.end_fill()
t.penup()


t.pencolor('yellow')
t.fillcolor('yellow')
t.begin_fill()
t.goto(-200,250)
t.pendown()
t.circle(30)
t.end_fill()
t.penup()

t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.goto(200,250)
t.pendown()
t.circle(20)
t.end_fill()

t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.goto(215,250)
t.pendown()
t.circle(20)
t.end_fill()

t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.goto(225,250)
t.pendown()
t.circle(20)
t.end_fill()

t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.goto(235,250)
t.pendown()
t.circle(20)
t.end_fill()
t.penup()



t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.goto(-50,250)
t.pendown()
t.circle(20)
t.end_fill()

t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.goto(-65,250)
t.pendown()
t.circle(20)
t.end_fill()

t.pencolor('white')
t.fillcolor('white')
t.begin_fill()
t.goto(-75,250)
t.pendown()
t.circle(20)
t.end_fill()
t.penup()

t.pencolor('gold')
t.fillcolor('gold')
t.goto(190,125)
t.begin_fill()
t.pendown()
t.goto(200,170)
t.goto(210,125)
t.goto(180,150)
t.goto(220,150)
t.goto(190,125)

#this i the last line of code
turtle.done()